Application1/app/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from app.config import Config
from app.main.routes import main

bcrypt = Bcrypt()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    bcrypt.init_app(app)


    app.register_blueprint(main)



    return app

Application1/app/main/routes.py
from flask import render_template, request, Blueprint, jsonify
from app.api_call_pred import api_call
import datetime
import json
import traceback

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    return render_template('index.html')

@main.route("/interaction")
def interaction():
    return render_template('interaction.html')

@main.route("/abstract")
def abstract():
    return render_template('abstract.html')

@main.route("/map")
def map():
    return render_template('predictionmap1.html')


@main.route('/prediction', methods=['POST'])
def prediction():
    try:
        req_data = request.get_json()
        origin = req_data['origin']
        destination = req_data['destination']
        date_time = req_data['datetime']

        tm = datetime.datetime.strptime(date_time,'%Y/%m/%d %H:%M').strftime('%Y-%m-%dT%H:%M')

        out = api_call(origin, destination, tm)

        return json.dumps(out)

    except:

        return jsonify({'trace': traceback.format_exc()})

Application1/app/templates/abstract.html
<!DOCTYPE HTML>
<html>
	<head>
		<title>Analysis and Prediction of Road TrafficAccident</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{{ url_for('static', filename='css/final_css_file.css') }}"/>
	</head>
	<body class="is-preload">

		<header id="header">
				<a href="{{ url_for('main.home') }}" class="title">Road Accident Analysis and Prediction</a>
				<nav>
					<ul>
						<li><a href="{{ url_for('main.home') }}">Home</a></li>
						<li><a href="{{ url_for('main.abstract') }}" class="active">Abstract</a></li>
					</ul>
				</nav>
			</header>
<section id="intro" class="wrapper style1 fullscreen fade-up">
						<div class="inner">
							<i><p>

Road accidents are one of the major causes of deadly injuries and deaths. It is possible to predict the possibility of accidents by studying past data. The occurrence of road accidents is associated with multiple factors such as speed, traffic condition, day, time, weather conditions, road construction, etc. The Government of the UK have made available quality datasets of Road accidents and their correlated factors. By studying these datasets and other data sources, we aim to develop a model that predicts with accuracy when and where an accident is likely to occur. With the help of machine learning tools and concepts this goal can be achieved.<p>
Our goal is to create an accurate road accidents prediction model that is a user-friendly and interactive web interface that allows users to enter the Date and time of travel along with the starting and destination locations and predict the probabilities of accidents occurring on the path of interest.<p>
The key steps involved are data pre-processing, Training the model with supervised learning algorithms and creation of the interactive Dashboard. The supervised learning algorithms Random Forest and Logistic regression are implemented and assessed on the basis of accuracy and performance for the training of the model. The unsupervised learning technique, DBSCAN algorithm is used for clustering of the data. The clustering is done as a data pre-processing step.
 <p>
The outcome of this project will benefit the travellers in providing a visualization tool that will evaluate the probability of an accident. In addition, it will help the traffic department in implementing strategies to reduce Road accidents.



							 
							 </p></i>
						</div>
					</section>

<footer id="footer" class="wrapper style1-alt">
				<div class="inner">
					<ul class="menu">
						<li>Group 46: MKSSS's Cummins college of engineering for women, Pune</li>						
					</ul>
				</div>
			</footer>

		<!-- Scripts -->

			<script src="static/js/jquery.min.js"></script>
			<script src="static/js/jquery.scrollex.min.js"></script>
			<script src="static/js/jquery.scrolly.min.js"></script>
			<script src="static/js/browser.min.js"></script>
			<script src="static/js/breakpoints.min.js"></script>
			<script src="static/js/util.js"></script>
			<script src="static/js/main.js"></script>

	</body>
</html>

Application1/app/templates/index.html
<!DOCTYPE HTML>
<html>
	<head>
		<title>Analysis and Prediction of Road Accident</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{{ url_for('static', filename='css/final_css_file.css') }}"/>
	</head>
	<body class="is-preload">
			<section id="sidebar">
				<div class="inner">
					<nav>
						<ul>
							<li><a href="#intro">INTRODUCTION</a></li>
							<li><a href="#interact">INTERACTION</a></li>
							<li><a href="#abstract">PROJECT OVERVIEW</a></li>
							 <li><a href="#team">GROUP DETAILS</a></li>

						</ul>
					</nav>
				</div>
			</section>


			<div id="wrapper">


					<section id="intro" class="wrapper style1 fullscreen fade-up">
						<div class="inner">
							<h1>Prediction of Road Traffic Accidents</h1>
							<p><i>
							Road Traffic Accidents are a major cause of death worldwide leading to around 1.35 million deaths and 50 million injuries every year that is, one person is killed every 25 seconds.<p>Hence, we aim to serve you with this platform which wil give you an idea about all the accidents that may occur on your route of interest and you plan your journey accordingly. </p>
							 </p></i>
						</div>
					</section>

					
					<section id="interact" class="wrapper style1 fade-up">
						<div class="inner">
							<h2>Interactive Page</h2>
							<p>Using Machine Learning tools and libraries this prediction visualization is developed . Click the below tab to visit this interactive Dashboard.</p>

							<ul class="actions">
								<li><a href="{{ url_for('main.interaction') }}"class="button">INTERACT</a></li>
							</ul>
						</div>
					</section>

					 <section id="abstract" class="wrapper style1 fade-up">
						<div class="inner">
							<h2>PROJECT OVERVIEW</h2>
							<p>This is the entire abstract of this project.</p>
							<ul class="actions">
								<li><a href="{{ url_for('main.abstract') }}"class="button">ABSTRACT</a></li>
							</ul>
						</div>
					</section>

					<section id="team" class="wrapper style1 fade-up">
						<div class="inner">
							<h2>TEAM DETAILS</h2>
							<p><i>This project is done by students of cummins college of Engineering for women, pune<br>
								Departmet of Electronics and telecommunications<br>
									Under The Guidance of Prof. Mrudul Dixit<br>
										Team Members<br>
										C22016111041 : Sai Gopal Deshmukh<br>
										C22016111034 : Mannase Dongaonkar<br>
									C22016111038 : Snehal Vilas Jadhav</i></h3></p>
							
						</div>
					</section>

			</div>

			<footer id="footer" class="wrapper style1-alt">
				<div class="inner">
					<ul class="menu">
						<li>Group 46: MKSSS's Cummins college of engineering for women, Pune</li>						
					</ul>
				</div>
			</footer>


			<script src="static/js/jquery.min.js"></script>
			<script src="static/js/jquery.scrollex.min.js"></script>
			<script src="static/js/jquery.scrolly.min.js"></script>
			<script src="static/js/browser.min.js"></script>
			<script src="static/js/breakpoints.min.js"></script>
			<script src="static/js/util.js"></script>
			<script src="static/js/main.js"></script>

	</body>
</html>

Application1/app/templates/interaction.html
<!DOCTYPE HTML>
<html>
	<head>
		<title>Interaction</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="{{ url_for('static', filename='css/final_css_file.css') }}" />
		<noscript><link rel="stylesheet" href="static/css/noscript.css" /></noscript>
	</head>
	<body class="is-preload">

			<header id="header">
				<a href="{{ url_for('main.home') }}" class="title">Road Accident Analysis and Prediction</a>
				<nav>
					<ul>
						<li><a href="{{ url_for('main.home') }}">Home</a></li>
						<li><a href="{{ url_for('main.interaction') }}" class="active">Interaction</a></li>
					</ul>
				</nav>
			</header>

			<div id="wrapper">

				<!-- Main -->
		<section id="main" class="wrapper">
			<div class="inner">

				<h1 class="major">Interactive Dashboard</h1>
				<p>We have created this map that allows you to find accident hotspots along the driving route between two locations at a particular time.</p>

				<p>To use the map we need to give the following inputs <br />
					(1) a date and time<br />
					(2) Starting location <br />
					(3) Destination <br />

				<p>
					Your route will be shown on the map.
					We will then feed all these inputs to our predictive model, which will give us the corresponding road accident risk on the map.	
				</p>


				<!--Date time picker-->
			<div class='col-lg-9'>
					<iframe src="{{ url_for('main.map') }}" name="iframe_a" style="height:800px;width:1300px;border: 2px steelblue solid;padding: 15px;margin: 15px"></iframe>
			</div>

			<!-- Footer -->
			<footer id="footer"  style="position:relative; bottom:0;clear:both" >
				<div class="inner">
					<ul class="menu">
						<li>Group 46:MKSSS's Cummins college of Engineering for women, Pune</li>
					</ul>
				</div>
			</footer>
		</section>
	</div>



		<!-- Scripts -->
			<script src="static/js/d3-tip.min.js"></script>
			<script src="static/js/interaction.js"></script>
			<script src="static/js/jquery.min.js"></script>
			<script src="static/js/jquery.scrollex.min.js"></script>
			<script src="static/js/jquery.scrolly.min.js"></script>
			<script src="static/js/browser.min.js"></script>
			<script src="static/js/breakpoints.min.js"></script>
			<script src="static/js/util.js"></script>
			<script src="static/js/main.js"></script>


	</body>
</html>

Application1/app/templates/predictionmap1.html
<!DOCTYPE html>
<html>
<head>
    <title>Place Autocomplete and Directions</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/jquery.datetimepicker.min.css') }}"/>
    <style>
        #loading {
              width: 100%;
              height: 100%;
              top: 0;
              left: 0;
              position: fixed;
              display: block;
              opacity: 0.7;
              background-color: #fff;
              z-index: 99;
              text-align: center;
              }
        #loading-image {
              position: absolute;
              top: 100px;
              left: 240px;
              z-index: 100;
              }
        /* Always set the map height explicitly to define the size of the div
         * element that contains the map. */
        #map {
            height: 100%;
        }
        /* Optional: Makes the sample page fill the window. */
        html, body {
            height: 100%;
            margin: 0;
            padding: 0;
        }
        .controls {
            margin-top: 10px;
            border: 1px solid transparent;
            border-radius: 2px 0 0 2px;
            box-sizing: border-box;
            -moz-box-sizing: border-box;
            height: 32px;
            outline: none;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        }
        #datetime-input,
        #origin-input,
        #destination-input {
            background-color: #fff;
            font-family: Roboto;
            font-size: 15px;
            font-weight: 300;
            margin-left: 12px;
            padding: 0 11px 0 13px;
            text-overflow: ellipsis;
            width: 200px;
        }
        #origin-input:focus,
        #destination-input:focus {
            border-color: #4d90fe;
        }
        #mode-selector {
            color: #fff;
            background-color: #4d90fe;
            margin-left: 12px;
            padding: 5px 11px 0px 11px;
        }
        #mode-selector label {
            font-family: Roboto;
            font-size: 13px;
            font-weight: 300;
        }
    </style>
</head>
<body>
  <!-- add loading screen-->
  <div id="loading">
    <img id="loading-image" src="https://cdn-images-1.medium.com/max/800/1*9EBHIOzhE1XfMYoKz1JcsQ.gif" alt="Loading..." />

  </div>


<div style="display: none">
    <input id="origin-input" class="controls" type="text"
           placeholder="Enter an origin location">

    <input id="destination-input" class="controls" type="text"
           placeholder="Enter a destination location">

    <input id="datetime-input"  class="controls" type="text" autocomplete="off" name="datetime"
          placeholder="Enter a date and time" >
    <input id="refresh" type="reset" value="Next Prediction" onClick="document.location.reload(true)">
</div>

<div id="map"></div>

<script>
    // This example requires the Places library. Include the libraries=places
    // parameter when you first load the API. For example:
    // <script
    // src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&libraries=places">
    var map;
    var markers = [];
    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            mapTypeControl: false,
            center: {lat: 51.5058, lng: -0.1},
            zoom: 13
        });
        new AutocompleteDirectionsHandler(map);
    }
    /**
     * @constructor
     */
    function AutocompleteDirectionsHandler(map) {
        this.map = map;
        this.originPlaceId = null;
        this.destinationPlaceId = null;
        this.travelMode = 'DRIVING';
        this.directionsService = new google.maps.DirectionsService;
        this.directionsDisplay = new google.maps.DirectionsRenderer;
        this.directionsDisplay.setMap(map);
        //datetime picker
       $(function () {
            var date = new Date();
            var currentMonth = date.getMonth();
            var currentYear = date.getFullYear();
            var currentDate = date.getDate() + 2;
           $("#datetime-input").datetimepicker({maxDate: new Date(currentYear, currentMonth, currentDate)});
       });
        var originInput = document.getElementById('origin-input');
        var destinationInput = document.getElementById('destination-input');
        var datetimeInput = document.getElementById('datetime-input');
        // var modeSelector = document.getElementById('mode-selector');
        var originAutocomplete = new google.maps.places.Autocomplete(originInput);
        // Specify just the place data fields that you need.
        originAutocomplete.setFields(['place_id']);
        var destinationAutocomplete =
            new google.maps.places.Autocomplete(destinationInput);
        // Specify just the place data fields that you need.
        destinationAutocomplete.setFields(['place_id']);

        this.setupPlaceChangedListener(originAutocomplete, 'ORIG');
        this.setupPlaceChangedListener(destinationAutocomplete, 'DEST');
        this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(datetimeInput);
        this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(originInput);
        this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(destinationInput);
        this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(refresh);
        // this.map.controls[google.maps.ControlPosition.TOP_LEFT].push(modeSelector);
    }

    AutocompleteDirectionsHandler.prototype.setupPlaceChangedListener = function(
        autocomplete, mode) {
        var me = this;
        autocomplete.bindTo('bounds', this.map);
        autocomplete.addListener('place_changed', function() {
            var place = autocomplete.getPlace();
            if (!place.place_id) {
                window.alert('Please select an option from the dropdown list.');
                return;
            }
            if (mode === 'ORIG') {
                me.originPlaceId = place.place_id;
            } else {
                me.destinationPlaceId = place.place_id;
            }
            me.route();
        });
    };
    AutocompleteDirectionsHandler.prototype.route = function() {
        if (!this.originPlaceId || !this.destinationPlaceId) {
            return;
        }
        var me = this;
        // Sending and receiving data in JSON format using POST method
        var xhr = new XMLHttpRequest();
        var url = "{{ url_for('main.prediction') }}";
        xhr.open("POST", url, true);
        xhr.setRequestHeader("Content-Type", "application/json");
        xhr.onreadystatechange = function () {
            if (xhr.readyState === 4 && xhr.status === 200) {
                var json = JSON.parse(xhr.responseText);
                console.log(json);
                //if no accident, alert user, else display icons
                if(json == null ) {window.alert('Hooray! No accidents predicted in your route. Click "Next Prediction" to reset map.');}
                else {showAccidents2(json); }
            }
        };
        var data = JSON.stringify({"origin": document.getElementById("origin-input").value,
                                    "destination": document.getElementById("destination-input").value,
                                    "datetime": document.getElementById("datetime-input").value});
        xhr.send(data);
         this.directionsService.route(
             {
                 origin: {'placeId': this.originPlaceId},
                 destination: {'placeId': this.destinationPlaceId},
                 travelMode: this.travelMode
             },
            function(response, status) {
                 if (status === 'OK') {
                     me.directionsDisplay.setDirections(response);
                 } else {
                     window.alert('Directions request failed due to ' + status);
                 }
             });
    };
    function showAccidents2(accident_json) {

        var icon = {
          url:'https://cdn3.iconfinder.com/data/icons/map-markers-1/512/death-512.png',
          scaledSize: new google.maps.Size(50, 50), // scaled size
        };

        var count = Object.keys(accident_json.accidents).length;
        console.log(count);
        window.alert(count + ' accidents predicted on your way. Check the pin point for the probability!');
        setMapOnAll(null);
        markers = [];
            for(var i = 0; i < count; i++)
                {
                    var marker = new google.maps.Marker({
                        position: new google.maps.LatLng( accident_json.accidents[i].lat, accident_json.accidents[i].lng),
                        map: map,
                        icon: icon,
                        title: 'Probability: ' + accident_json.accidents[i].probability.toString()
                    });
                    markers.push(marker);
                }
        // marker.setMap(map);
        setMapOnAll(map);
    }
    // Sets the map on all markers in the array.
    function setMapOnAll(map) {
        for (var i = 0; i < markers.length; i++) {
            markers[i].setMap(map);
        }
    }
    //var markerArray = [];
    function showSteps(directionResult) {
        // For each step, place a marker, and add the text to the marker's
        // info window. Also attach the marker to an array so we
        // can keep track of it and remove it when calculating new
        // routes.
        var myRoute = directionResult.routes[0].legs[0];
        for (var i = 0; i < myRoute.steps.length; i++) {
            var marker = new google.maps.Marker({
                position: myRoute.steps[i].start_point,
                map: map
            });
            // console.log("Step:" + i + "," + myRoute.steps[i].start_point);
            attachInstructionText(marker, myRoute.steps[i].instructions);
            //markerArray[i] = marker;
        }
    }
    function attachInstructionText(marker, text) {
        google.maps.event.addListener(marker, 'click', function() {
            stepDisplay.setContent(text);
            stepDisplay.open(map, marker);
        });
    }
// https://stackoverflow.com/questions/1006654/fastest-way-to-find-distance-between-two-lat-long-points
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB2OauQvIUxxEequvInYsXFB_D_NhsRvGw&libraries=places&callback=initMap"
        async defer></script>
<script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.datetimepicker.full.js') }}"></script>
<script language="javascript" type="text/javascript">
     $(window).load(function() {
     $('#loading').hide();
  });
</script>
</body>
</html>